// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAl3pfb6GSlMhRDhZnDGWM7MtUawo8SdCo',
    appId: '1:912749325449:android:16a8c7f69f6fb2cd5b2a58',
    messagingSenderId: '912749325449',
    projectId: 'eden-work-sample',
    storageBucket: 'eden-work-sample.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjNvykbEq6crTJt0rIN2dPCMbgdi_1tzY',
    appId: '1:912749325449:ios:76856697178ff2ae5b2a58',
    messagingSenderId: '912749325449',
    projectId: 'eden-work-sample',
    storageBucket: 'eden-work-sample.appspot.com',
    androidClientId: '912749325449-4dvvv9q7vn5bovtu60lr6dprhg32lhtr.apps.googleusercontent.com',
    iosClientId: '912749325449-lsp6b66hdh3stl0fmdnd2vqg7lse2ros.apps.googleusercontent.com',
    iosBundleId: 'com.example.edenWorkSample',
  );
}
